run:
  timeout: 3m
linters:
  enable:
    - bodyclose
    - errorlint
    - exportloopref
    - goconst
    - goimports
    - gosec
    - ifshort
    - nilerr
    - stylecheck
    - unparam
    - wastedassign
linters-settings:
  errcheck:
    exclude: .errcheck_excludes.txt
